language: java
sudo: required

jdk:
  - oraclejdk8

services:
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('password') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -ppassword
  - sudo service mysql restart

before_script:
  - mysql -u root -ppassword -e 'CREATE DATABASE IF NOT EXISTS PhotoPondTest;'
  - mysql -u root -ppassword -e "GRANT ALL ON PhotoPondTest.* TO 'travis'@'%';"

script:
  - mvn clean package -B -Dapplication.location=${HOME}

after_script:
  - echo "Script finished"

after_success:
  - echo "Build was successful. $TRAVIS_TEST_RESULT"

after_failure:
  - echo "Build was failed"